### ISSUE TITLE
currently the code will fail when insts is not None

### ISSUE THREAD

**Issue by skylian** [idlrl/flare#31]
https://github.com/idlrl/flare/blob/eb683dcefe8cb640ce1ecdfe8d171d30cbb3099b/flare/framework/computation_task.py#L142
https://github.com/idlrl/flare/blob/eb683dcefe8cb640ce1ecdfe8d171d30cbb3099b/flare/framework/computation_task.py#L185
https://github.com/idlrl/flare/blob/eb683dcefe8cb640ce1ecdfe8d171d30cbb3099b/flare/framework/computation_task.py#L213

The step function and `Algorithm`'s `learn` function totally ignores `insts`.

**Comment by skylian** [comment]
We could add `insts` as an argument of `learn()` functions.

**Comment by yu239** [comment]
I think there is no longer need for insts any more. We can directly use a static tensor inside a step function in PyTorch.

**Comment by yu239** [comment]
insts shouldn't be an argument of learn(). It should be an argument of the general recurrent API you are working on.
