### ISSUE TITLE
Should we have a detailed description of the data protocol between agent and CDP

### ISSUE THREAD

**Issue by wangyang59** [idlrl/flare#35]
I found that the definition of the data protocol was not clear to me when I tried to write my own agent for XWorld env. For example, why https://github.com/idlrl/flare/blob/master/flare/agent_zoo/simple_rl_agents.py#L23 feeds observations[0] to sensor while https://github.com/idlrl/flare/blob/master/flare/agent_zoo/simple_rl_agents.py#L29 feeds observations to sensor. 

Also, in https://github.com/idlrl/flare/blob/master/flare/agent_zoo/simple_rl_agents.py#L29 actions.value()[0][0] is quite opaque to me. I feel that a more detailed description of how the data is transferred between agent and CDP is required in the tutorials

**Comment by yu239** [comment]
See PR #37
