### ISSUE TITLE
where to put `torch.no_grad()`

### ISSUE THREAD

**Issue by skylian** [idlrl/flare#7]
https://github.com/idlrl/flare/blob/40ace8af072822cfb53d005ba5158fd172fc9213/flare/framework/computation_task.py#L73

I think we need to discuss where to put `torch.no_grad()`. In my opinion, CT shouldn't know such thing.

**Comment by yu239** [comment]
For prediction(), it is always needed to put no_grad wrapping around it. So instead of requiring the users to do this job every time, we can just wrap no_grad in CT.
